### PR TITLE
Csproj updated + Modernized build process

### PR DESCRIPTION
**Pull request by Kuinox**
Hello,
I updated the csproj, removed dlls in the Assemblies folder.
The dependents dll now come from the nuget packages.
Instead of relying on the dll loading order that imposeto rename the dll to be loaded in the right order, i added a post build task that merge all the dll, and put the final DLL in the Assemblies folder.
Also, 2 dlls (l18N & l182.West) were unused and removed.

### CODE REVIEW

**Comment by SweptWasTaken** [comment]
Requested NotFood look at this one, can't judge it.

**Comment by notfood** [comment]
Target fails to run on my end.

```
Target ILRepack:
    mono /media/Makai/home/.nuget/packages/ilrepack/2.0.18/build/../tools/ILRepack.exe ^
    System.ArgumentException: No output file given.
      at ILRepacking.RepackOptions.Validate () [0x00086] in <fa257496929944d3922e0349a0420534>:0 
      at ILRepacking.ILRepack.Repack () [0x0000c] in <fa257496929944d3922e0349a0420534>:0 
      at ILRepacking.Application.Main (System.String[] args) [0x0004a] in <fa257496929944d3922e0349a0420534>:0 
    /media/Mayohiga/opt/SteamLibrary/steamapps/common/RimWorld/Mods/Multiplayer/Source/Multiplayer.csproj(28,5): error MSB3073: The command "mono /media/Makai/home/.nuget/packages/ilrepack/2.0.18/build/../tools/ILRepack.exe ^" exited with code 1.
Done building target "ILRepack" in project "Multiplayer.csproj" -- FAILED.

Done building project "Multiplayer.csproj" -- FAILED.

Build FAILED.
```

**Comment by Kuinox** [comment]
It should works now, did not expected that you could build .Net framework on linux...

**Comment by Kuinox** [comment]
Removed ILrepack: it was not needed finally.

**Pull request merged**
