### PR TITLE
Session rework

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
Changes/additions:
- Added `SessionManager`
- The `SessionManager` will handle storing and processing all the sessions
- There's one `SessionsManager` for `MultiplayerWorldComp`, as well as one for each `MultiplayerMapComp`
- Sessions are now assigned an ID based on their own ID numbers, instead of using `Thing` IDs for that
- Instead of sessions self-assigning their own IDs, the IDs are now assigned by `SessionManager`
- All existing sessions were reworked to use the new system
- A `Session` class has been added which should be used by mods implementing their own sessions ~~(should we remove `ISession` interface and just use `Session` class?)~~
- The `Session` class includes a basic implementation for handling `SessionId`
- The `Session` class includes an empty virtual implementation for some methods which not all mods need to implement
- ~~The `Session` class exists (as opposed to just using `ISession`) as a way to make it easy to expand it without requiring the mods to update - the `Session` class will contain the basic implementation for all new methods in the future (should we do it with other interfaces?)~~
- `Session`, `ExposableSession`, and `SemiPersistentSession` were created instead of using interfaces to make it simpler to expand them in the future without requiring mods to update (by adding empty virtual methods as needed). Their respective interfaces were removed as they now served no purpose.
- The `Session` class includes a static method `SwitchToMapOrWorld` for convenience
- Pause locks were reworked to use the new session system, will only be used if there's any pause lock registered
- `SyncSessionWithTransferablesMarker.DrawnSessionWithTransferables` has been included, somewhat based on how `ThingFilterMarkers.DrawnThingFilter` is implemented, used for syncing Trasferables in `ISessionWithTransferables` sessions
- Unique sessions, as well as sessions with other restrictions, are handled by `ISessionWithCreationRestrictions` - they sadly need to be initialized to work (static members in interfaces seem to not be available in .NET used by RimWorld)

Some things that could be done:
- Include a cached field for all sessions when needing a specific session (caravan forming, caravan splitting, etc.), similarly to the list of trade sessions. Currently all but trading sessions are accessed through session manager.
- When adding a `Session` to the manager, only the session itself (if it's `ISessionWithCreationRestrictions`) checks if it should be added - any sessions already existing don't check against the one being added. This could be changed to work both ways.

Things left to do:
- Finish documentation for `ISessionManager`
- Add methods for `MultiplayerAPIBridge` that will be included in updated MP API for accessing `SessionManager`
- `ISessionWithTransferables` will require proper `<see cref=""/>` tags once included in the MP API.

Things that will need to be moved to MP API:
- `Session` class - possibly could use a rename
- `ISessionManager` interface
- All session related interfaces - the only exception could possibly be `IPausingWithDialog`, as it seems to be right now
- Should `ISwitchToMap` be included (and potentially expanded)?

Testing:
- I've tried to test every single existing sessions, including starting one, operating on it, and then joining with a second client, as well as just working with them and using them
- There could still be issues I haven't found, so it could use more testing

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
Pushed a commit that removed `ISession`, `IExposableSession`, and `ISemiPersistentSession` in favor of abstract classes `Session`, `ExposableSession`, and `SemiPersistentSession`. It was basically pointless to have those 3 interfaces. If needed it can be reverted.

**Comment by SokyranTheDragon** [comment]
I've added a sync dict entry for `ISessionWithTransferables`. It originally worked as it inherited from `ISession`, however - due to dropping the 3 interfaces it ended up no longer being syncable. This should fix it.

**Comment by SokyranTheDragon** [comment]
Working a bit with the new sessions, I've encountered a specific (and possibly rather niche) scenario.

I'm in a situations where I need to keep an event/quest/etc. map temporarily paused and alive. The mod itself would do it itself, but due to needing for syncing and some patches, I'm in a situation where it's not possible.

Keeping the map paused is rather easy with the sessions. However, this still requires the "keep alive" aspect implemented, so this made me wonder:

Would it be worthwhile to include to include `IBlocksMapRemoval` interface, or something along those lines (like `ISessionBlockingMapRemoval`). This would likely be done by patching `Verse.MapPawns::AnyPawnBlockingMapRemoval` property, where we'd likely checking the local (and possibly the global, depending on implementation) session managers for sessions blocking the map from being removed.

Anyway, this is just a minor thing to possibly consider. Checking this PR made me realize there are conflicts, so I'll look into resolving them in the next day or two.

**Comment by SokyranTheDragon** [comment]
Merged with the master branch and resolved the merge conflicts

**Comment by Zetrith** [comment]
Merged

**Pull request closed without merging**
