### PR TITLE
[WIP] Delay switching focus until white window is created.

### PR DESCRIPTION
**Pull request by lukaschristmann**
I tried to prevent creation of the white window under windows by passing CreateNoWindow=true,
but this only delays loss of focus until the white window actually is created (in contrast to when the arbiter is starting up)
I checked and 'RimWorldWin64.exe -batchmode -nographics' still seems to work on its own.

I'm still kinda lost as to where the startup actually begins, but i'll dig into that later today/tomorrow, but if anyone points me there or has other ideas i'd be glad

Edit:
Current State:
- It is a Rimworld bug, caused by -batchmode -nographics and loading a game, but it is probably not gonna be fixed soon by Ludeon.
- 

Ideas left to check:
- [x] Check startup sequence of arbiter for fuckups that could create a window
- [x] ...
- [x] Check MainTabWindow
- [x] Check Graphics_Mote
- [x] Check Verse.Window
- [ ] Check AlternateGraphic
- [ ] Check UIRoot

### CODE REVIEW

**Comment by lukaschristmann** [comment]
I'm out of ideas to check whether this is our fault. If you have any ideas left please comment here.

**Comment by Deathlymad** [comment]
i passed all combinations of [-arbiter, -batchmode, -nographics] in pretty muych all possible orders as well. the result was that the even the basegame would become a white window when only , -batchmode, -nographics were passed. That windows would not show when -quit was passed as well. (eventho the process was still running properly). However that was slightly insonsistent, one or two times it turned into the white walker window again, that might habe been related to the cast exceptions from above. I Also tried to go over ProcessStartInfo to disable the creation of the window unsuccessfully. Furthermore in the arbiter log says that a null renderer is forced, so the engine isn't trying to render anything. My current theory is that some part of the arbiter initializing data structures causes unity to require a window context not for rendering but for auxilliary stuff interfacing with the OS. like maybe a sound device or sth. for example both instances have an audio device registered

**Comment by Deathlymad** [comment]
Its also probably not related to ReloadGame.  i had the ReloadGame function print on each line into the log and that happens well after the windows spawns

**Comment by Deathlymad** [comment]
Also i tested the same and also, what you did might not work due to 

startInfo.UseShellExecute = false

missing. 
I also tried:

startInfo.WindowStyle = ProcessWindowStyle.Hidden;

Both didn't work.

**Comment by Zombiefied7** [comment]
When opening Rimworld through Steam I get the same white window for a moment. You can recreate this easily by starting Rimworld in non-fullscreen low resolution.

About "ReloadGame" function:
The window still appears even if ReloadGame is never called as seen in my screenshot above. ReloadGame does cause the same problem because thats where the savegame is loaded

One thing that could be helpful is trying to run Vanilla RimWorld without the MPmod in -batchmode -nographics and make it open a savegame. That way we can tell if the window opens without MPmod

Im thinking about using "-parentHWND <HWND> delayed" (Unity command line argument, <HWND> being the Process' MainWindow Handle) to parent the main RimWorld process to the Arbiter process. Then you can access the arbiter-window and hide it manually.

Another solution could be using user32.dll to manually hide the window, again using the MainWindow Handle. Here Im having trouble importing the user32.dll as RimWorld will try to interpret it as a mod.

The last 2 are workarounds tho and not really fixing the problem

**Comment by Deathlymad** [comment]
to test the behavior of the arguments i did run various sets of them on vanilla rimworld. just starting it with -batchmode -nographics turns it into a white walker, i don't see how loading a save would affect that.

**Comment by Deathlymad** [comment]
I did some more digging. the additional argument ` -force-gfx-direct` fixes it on my system. That being said due to the nature of that argument its probably a good idea to test it on different graphic systems. And to check whether this doesn't brick things on linux or mac. 
Mine is: (from output_log.txt)
```
Direct3D:
    Version:  Direct3D 9.0c [nvldumdx.dll 26.21.14.4219]
    Renderer: NVIDIA GeForce GTX 1080
    Vendor:   NVIDIA
    VRAM:     8079 MB (via DXGI)
    Caps:     Shader=30 DepthRT=1 NativeDepth=1 NativeShadow=1 DF16=0 INTZ=1 NULL=1 RESZ=0 SlowINTZ=0 ATOC=1 BC4=1 BC5=1
```

**Comment by Noires** [comment]
If i debug Rimworld those are the last things happening before showing the white screen. Not sure if helpful atm though.
```
16:30:57.724 RimWorldWin64.exe (Unity: Unity Root Domain): Loaded 'Anonymously Hosted DynamicMethods Assembly'.
16:31:02.733 Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
16:31:02.735 Additional information: Could not find a part of the path "E:\Program Files (x86)\Rimworld\Data\Core\Languages\English\WordInfo\Gender\Male.txt".
16:31:02.737 Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
16:31:02.739 Additional information: Could not find a part of the path "E:\Program Files (x86)\Rimworld\Data\Core\Languages\English\WordInfo\Gender\Female.txt".
16:31:02.741 Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
16:31:02.743 Additional information: Could not find a part of the path "E:\Program Files (x86)\Rimworld\Data\Core\Languages\English\WordInfo\Gender\Neuter.txt".
16:31:02.758 Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
16:31:02.760 Additional information: Could not find a part of the path "E:\Program Files (x86)\Rimworld\Mods\Multiplayer\Languages\English\WordInfo\Gender\Male.txt".
16:31:02.762 Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
16:31:02.764 Additional information: Could not find a part of the path "E:\Program Files (x86)\Rimworld\Mods\Multiplayer\Languages\English\WordInfo\Gender\Female.txt".
16:31:02.767 Exception thrown: 'System.IO.DirectoryNotFoundException' in mscorlib.dll
16:31:02.769 Additional information: Could not find a part of the path "E:\Program Files (x86)\Rimworld\Mods\Multiplayer\Languages\English\WordInfo\Gender\Neuter.txt".
16:31:02.945 Exception thrown: 'System.Net.Sockets.SocketException' in System.dll
16:31:02.947 Additional information: Normalerweise darf jede Socketadresse (Protokoll, Netzwerkadresse oder Anschluss) nur jeweils einmal verwendet werden. <- this is a socket exception that each socket adress can only be used once not sure why it is translated for me there~
16:31:02.949 
16:31:03.807 Exception thrown: 'System.NullReferenceException' in data-000001BCE7FE6E70
16:31:03.809 Additional information: Object reference not set to an instance of an object

```

**Comment by Zombiefied7** [comment]
I tested setting up a new mod that does nothing but open another instance of Rimworld and load a savegame in -batchmode. The white walker window still happens. That means the issue is caused by RimWorld not the MPmod. That doesnt mean we cant fix it tho.

**Comment by Zombiefied7** [comment]
What we know is the window appears only as soon as a savegame is loaded so we can try to remove some functions that only happen when a savegame is loaded for example RenderPawnAt(), im trying that right now

**Comment by Noires** [comment]
image

Something i noticed when comparing the 1.0 and 1.1 Assembly-CSharp.dll. Will continue updating this with differences i find.

**Comment by lukaschristmann** [comment]
MainTabWindow seems unrelated, i programmatically patched all subclasses of Verse.Window (Which MainTabWindow is one of) ([Resulting list from patch output](https://gist.github.com/lukaschristmann/f4af6e9c6c8dc3e523baa3148fb5e5fc)) to prevent their constructor in the arbiter, but i still got a white window...

**Comment by Deathlymad** [comment]
```

namespace Verse
{
    public class Graphic_MotePulse : Graphic_Mote
    {
        protected override bool ForcePropertyBlock
        {
            get
            {
                return true;
            }
        }

        public Graphic_MotePulse()
        {
        }

        public override void DrawWorker(Vector3 loc, Rot4 rot, ThingDef thingDef, Thing thing, float extraRotation)
        {
            Mote mote = (Mote)thing;
            Graphic_Mote.propertyBlock.SetColor(ShaderPropertyIDs.Color, this.color);
            Graphic_Mote.propertyBlock.SetFloat(ShaderPropertyIDs.AgeSecs, mote.AgeSecs);
            base.DrawMoteInternal(loc, rot, thingDef, thing, 0);
        }

        public override string ToString()
        {
            return string.Concat(new object[] { "Graphic_MotePulse(path=", this.path, ", shader=", base.Shader, ", color=", this.color, ", colorTwo=unsupported)" });
        }
    }
}
```
Is new in 1.1 and looks conspicous to me. 
If i understand batch mode correctly, i think it should be a call for generating some kind of texture or generally anything that could be concivably done on the GCard that doesn't generate any presentable output. Because in that case it would make sense for unity, detecting that there is a GFX device, to create a context for it even while being extensibly intended to data crunch. Because it could be faster with that context. 
The audio device also spawns if you run rimworld vanilla in batchmode without the window and its not related to anything save related either so the cause is probably not there.

**Comment by lukaschristmann** [comment]
I don't think the audio device is a problem, i checked today and it doesn't output sound as the mod somewhere does something like "Game.Settings.Volume=0" - so the audio device probably was there even in 1.0

**Comment by lukaschristmann** [comment]
> Is new in 1.1 and looks conspicous to me.

mh, it seems to boil down to a Graphics.DrawMesh in the call stacks that might actually create a window, but... if i take a patch to just completely skip that function... still a white window :-\

```
    [HarmonyPatch]
    static class ArbiterPreventWhiteWindowPatch
    {
        static IEnumerable<MethodBase> TargetMethods()
        {
            yield return AccessTools.Method(typeof(Graphics), "DrawMesh",
                new[]
                {
                    typeof(Mesh), typeof(Matrix4x4), typeof(Material), typeof(int), typeof(Camera), typeof(int),
                    typeof(MaterialPropertyBlock), typeof(ShadowCastingMode), typeof(bool), typeof(Transform),
                    typeof(LightProbeUsage), typeof(LightProbeProxyVolume)
                });
            yield return AccessTools.Constructor(typeof(Graphic_Mote));
            yield return AccessTools.Constructor(typeof(Graphic_Single));
        }
        static bool Prefix() => !MultiplayerMod.arbiterInstance;
    }
```

**Comment by Deathlymad** [comment]
Another new class that has the possibility is
```

namespace Verse
{
    public class AlternateGraphic
    {
        private float weight = 0.5f;

        private string texPath;

        private Color? color;

        private Color? colorTwo;

        private GraphicData graphicData;

        public float Weight
        {
            get
            {
                return this.weight;
            }
        }

        public AlternateGraphic()
        {
        }

        public Graphic GetGraphic(Graphic other)
        {
            if (this.graphicData == null)
            {
                this.graphicData = new GraphicData();
            }
            this.graphicData.CopyFrom(other.data);
            if (!this.texPath.NullOrEmpty())
            {
                this.graphicData.texPath = this.texPath;
            }
            GraphicData graphicDatum = this.graphicData;
            Color? nullable = this.color;
            graphicDatum.color = (nullable.HasValue ? nullable.GetValueOrDefault() : other.color);
            GraphicData graphicDatum1 = this.graphicData;
            nullable = this.colorTwo;
            graphicDatum1.colorTwo = (nullable.HasValue ? nullable.GetValueOrDefault() : other.colorTwo);
            return this.graphicData.Graphic;
        }
    }
}

```
In Particular `  this.graphicData = new GraphicData(); ` since there are shader Objects constructed if i tracked it correctly. Following the previous theory, it would request a GFXObject even when nothing is presented with it.

**Comment by Deathlymad** [comment]
This is a big long to copy pasta, but another canidate are the changes in `Verse.Window` .
In particular there is a restructuring of the functions `Window()`, `WindowOnGUI` and a creation of the function `InnerWindowOnGUI`

**Comment by Deathlymad** [comment]
I just tried a third method of trying to figure out the spawning of the window. I just disabled the constructor to the UI Root and see what crashes. The Result of:
```

    [HarmonyPatch]
    static class ArbiterPreventWhiteWindowPatch
    {
        static IEnumerable<MethodBase> TargetMethods()
        {
            yield return AccessTools.Constructor(typeof(UIRoot_Play));
            yield return AccessTools.Constructor(typeof(UIRoot));
            yield return AccessTools.Constructor(typeof(UIRoot_Entry));
            yield return AccessTools.Method(typeof(UIRoot_Entry), "UIRootUpdate");
            yield return AccessTools.Method(typeof(UIRoot_Play), "UIRootUpdate");
            yield return AccessTools.Method(typeof(UIRoot_Entry), "UIRootOnGUI");
            yield return AccessTools.Method(typeof(UIRoot_Play), "UIRootOnGUI");
            yield return AccessTools.Method(typeof(UIRoot), "UIRootUpdate");
            yield return AccessTools.Method(typeof(UIRoot), "UIRootOnGUI");
        }
        static bool Prefix() => !MultiplayerMod.arbiterInstance;
    }
```
Is, that the Exception:
```

Exception from asynchronous event: System.NullReferenceException: Object reference not set to an instance of an object
  at Verse.Game.set_CurrentMap (Verse.Map value) [0x0003a] in <000153db58284aa38698b9c41ca1154b>:0 
  at (wrapper dynamic-method) Verse.Game.DMD<DMD<LoadGame_Patch4>?-1166165376::LoadGame_Patch4>(Verse.Game)
  at Multiplayer.Client.LoadPatch.Prefix () [0x0003a] in <2bc2dbdb930e44ab862006d80282075c>:0 
  at (wrapper dynamic-method) Verse.SavedGameLoaderNow.DMD<DMD<LoadGameFromSaveFileNow_Patch1>?-1875243392::LoadGameFromSaveFileNow_Patch1>(string)
  at Verse.Root_Play+<>c.<Start>b__1_1 () [0x00005] in <000153db58284aa38698b9c41ca1154b>:0 
  at Verse.LongEventHandler.RunEventFromAnotherThread (System.Action action) [0x00008] in <000153db58284aa38698b9c41ca1154b>:0 
 ```
I don't have time right now to figure out how to get around that but i think that might be what we are loking for.

**Comment by Noires** [comment]
Experiment 1:

1. Building multiplayer mod with the current unstable branch (1.1+)
- a slightly modified version so it doesn't automatically start the new process with the connect parameters but shows the port the arbiter should connect to
2. Starting the server with the current unstable branch (1.1+)
3. Starting the client with the parameters to connect as the arbiter with a modified version of the unstable rimworld (1.1+) by replacing the Assembly-CSharp.dll and Assembly-CSharp-firstpass.dll with the 1.0 versions of the dlls

**The white window still appears and then obviously the application crashes after a few seconds. That lets me just assume that it is more a issue with Unity or atleast Unity related.**

Experiment 2:
Hiding the white window with tools like http://www.window-hide.com/ after appearing works. So it might really be worthwhile to just do it kinda the hacky way than to waste time with it. Could hide the window directly after appearing and setting focus back to main application, which would still be annoying but better than how it is now.

**Comment by Noires** [comment]
Following approach works with a delay of course (might need to adjust where to hide the window).
Doing it inside the Multiplayer Mod directly didn't work consistently because of MainWindowHandle being 0, which i could not fix yet.

In **Multiplayer.cs** at **HandleCommandLine()** I added:
```
            if (GenCommandLine.CommandLineArgPassed("arbiter"))
            {
                username = "The Arbiter";
                Prefs.VolumeGame = 0;
                var args = Process.GetCurrentProcess().Id.ToString();
                using (Process myProcess = new Process())
                {
                    Log.Message("Process arguments:" + args);
                    myProcess.StartInfo.UseShellExecute = false;
                    myProcess.StartInfo.FileName = "C:\\Users\\Corvus\\Source\\Repos\\Rimworld\\RimWorldWindowHider.exe";
                    myProcess.StartInfo.Arguments = args;
                    myProcess.StartInfo.CreateNoWindow = true;
                    myProcess.Start();
                }
            }
```

The console app:
```
    class Program
    {
        private const int SW_HIDE = 0;
        [DllImport("User32")]
        private static extern int ShowWindow(int hwnd, int nCmdShow);

        static void Main(string[] args)
        {
            if (args is null || !args.Any())
            {
                return;
            }
            var processId = int.Parse(args[0]);
            if (processId != 0)
            {
                int hWnd;
                Process process = Process.GetProcessById(processId);
                process.Refresh();
                hWnd = process.MainWindowHandle.ToInt32();
                ShowWindow(hWnd, SW_HIDE);
            }
            return;
        }
    }
```

So this might be a terrible option atleast? Just don't know if a mod with an executable would even be a thing.

**Comment by Noires** [comment]
Based on the information from before that unity can't retrieve the MainWindowHandle: https://forum.unity.com/threads/unity-window-handle.115364/

```
        [System.Runtime.InteropServices.DllImport("user32.dll")]
        private static extern System.IntPtr GetActiveWindow();

        public static System.IntPtr GetWindowHandle()
        {
            return GetActiveWindow();
        }
```
In Multiplayer.cs at HandleCommandLine() I added:

```
            if (GenCommandLine.CommandLineArgPassed("arbiter"))
            {
                username = "The Arbiter";
                Prefs.VolumeGame = 0;
                int hWnd;
                hWnd = GetActiveWindow().ToInt32();
                ShowWindow(hWnd, SW_HIDE);
            }
```
Still needs to be verified by other people, but this works for me atleast.

**Comment by notfood** [comment]
That won't do, at least you must make it multiple OS aware. It'll crash on Linux and OSX.

**Comment by CryoRenegade** [comment]
I can test on OSX if needed

**Comment by Deathlymad** [comment]
I thought the bug was windows specific

**Comment by Noires** [comment]
At the moment, i'am unable to test solutions for Linux and OSX, if it occurs there aswell. Will still take a look at it tomorrow.

**Comment by notfood** [comment]
It doesn't happen on Linux. But that code will crash RW on Linux.

**Comment by Deathlymad** [comment]
@notfood would it be enough to put the whole thing in a `if (Application.platform == RuntimePlatform.WindowsPlayer)` or is a try catch better or would a more complicated implementation be needed?

Also @Noires your way of getting the window breaks if you deselect the rimworld window. I used this instead and it seems to always work: `hWnd = FindWindowA("Unity.BatchModeWindow", "Rimworld by Ludeon Studios").ToInt32();`
I am not sure it would be worth it to look into trying to invoke it any earlier since i don't think we could do sth about it without the multiplayer mod being loaded.

**Pull request closed without merging**
