### PR TITLE
Introduces ArbiterWhiteWindowHider for Windows (wip-1.1)

### PR DESCRIPTION
**Pull request by Noires**
Based on https://github.com/rwmt/Multiplayer/pull/17

### CODE REVIEW

**Comment by notfood** [comment]
Can you remove all the unrelated changes and focus your patch? It's adding a lot of unnecessary stuff.

**Comment by Noires** [comment]
I reverted it, but it was just the automatic formatting of Visual Studio and the style is really inconsistent.

**Comment by notfood** [comment]
Can anyone confirm it working? I can't test this.

**Comment by Deathlymad** [comment]
I can confirm that it works for me. There is a brief time frame where the window is showing. And, I will try this a couple more times but i think that also fixes the bug of the arbiter not restarting after you restart a server.

**Comment by Deathlymad** [comment]
After loading 3 different saves 4 times and also opening a singleplayer game as a server and the arbiter instance was loading each time, so that bug seems to be fixed as well. At least on windows.

**Comment by Noires** [comment]
I split the methods to put focus back to the main game earlier. Still not happy with the SW_MAXIMIZE in the method though, since it doesn't restore the previous state of the window. But the other values didn't seem to work for me.

**Comment by Zombiefied7** [comment]
Does not work for me.
I lose focus on RimWorld, then after a delay regain focus on RimWorld, then lose focus on RimWorld again when the Arbiter window appears. The Arbiter window does not close for me.
I think your method got called too early on my system but it might work with some tweaks so good job!

**Comment by Zombiefied7** [comment]
You should call your method after a map is loaded

**Comment by Deathlymad** [comment]
@Zombiefied7 whats your rimworld version, Noires noted it on the discord that after some fix the window plopped up significantly earlier.

**Comment by Zombiefied7** [comment]
At the time of my last comment I was on live version 1.1 but I have the same problem with version 1.1.2575

**Comment by Noires** [comment]
I delayed it again. Might be due to different loading time on different pc's.

**Comment by Deathlymad** [comment]
I just tested the new version of this pull request again and it still works for me. But there is this delay of dealing with the window until the arbiter has joined and everything is done.

**Comment by Zombiefied7** [comment]
I just tested ArbiterWhiteWindowHider.cs only and it works very well, good job!

Now we only need to think about when it should be called because best case we want it to close immediately.
This could be achieved by running the ArbiterHider methods every other tick for a few seconds after starting the Arbiter. Kinda whacky approach tho, what do you think?

**Comment by Deathlymad** [comment]
Ideally I'd just track down the calls that cause this but its been super unsuccessful.

**Comment by Zombiefied7** [comment]
```public class OnMainThread : MonoBehaviour
    {
        public static ActionQueue queue = new ActionQueue();

        public static int cachedAtTime;
        public static byte[] cachedGameData;
        public static Dictionary<int, byte[]> cachedMapData = new Dictionary<int, byte[]>();

        // Global cmds are -1
        public static Dictionary<int, List<ScheduledCommand>> cachedMapCmds = new Dictionary<int, List<ScheduledCommand>>();

        public void Update()
        {
            if (Environment.OSVersion.Platform.Equals(PlatformID.Win32NT) && Multiplayer.session != null && Multiplayer.session.arbiter != null && !Multiplayer.session.ArbiterPlaying)
            {
                ArbiterWhiteWindowHider.FocusRimworld();
                ArbiterWhiteWindowHider.HideArbiter();
            }```

What do you think about this approach

**Comment by Noires** [comment]
As soon as **static Multiplayer()** is called, i started a Task which tries to close the white window nonstop, but it still doesn't get closed earlier. Something just blocks the window for a moment and i am not sure how much we can do about this.

**Comment by Deathlymad** [comment]
I can imagine two reasons for that:
1. Rimworld takes some time to finish initializing the mods probably (that might make the problem even weirder)
2. The functions just send basically a request to the window handle. it needs to be processed too. I could picture that loading/blocking threads would delay such handling.

**Comment by Zombiefied7** [comment]
Please try the code I commented above, it works well for me

**Comment by Noires** [comment]
I will try it today and tell you the results asap 👍

**Comment by Noires** [comment]
@Zombiefied7 yeah works definitly quicker. I will take a closer look at it.

**Comment by Noires** [comment]
Thanks for the nice suggestion. I adjusted it though and moved it to the creation of the process to make it clearer.

**Comment by Zombiefied7** [comment]
Your new version does not work for me.

You should use !arbiterVisible instead of arbiterVisible == false. The way you did it will use up a lot of cpu time as you are checking if the window is visible non stop. You are only focusing RimWorld if the Arbiter is shown so RimWorld will be unfocused for a few seconds.

**Comment by Noires** [comment]
@Zombiefied7 Could you check again? Probably the pointer check was wrong after code cleanup...
It behaves now exactly the same as your suggestion for me atleast.

**Comment by Zombiefied7** [comment]
Still not working.

`CheckIfArbiterVisible()` always returns true. It seems this is not working correctly on every system.

On my system RimWorld unfocusing and Arbiter opening does not happen at the same time. Because of that, running `FocusRimworld()` and `HideArbiter()` only once will not be enough.
Instead I recommend doing it every tick inside your Task until the arbiter is resolved (this is not a big load). We know the arbiter is resolved when `Multiplayer.session.ArbiterPlaying` so you could use that instead of `CheckIfArbiterVisible()`. 

The problem with doing `FocusRimworld()` and `HideArbiter()` every tick is that focus will constantly be forced on RimWorld so alt+tab wont work for while the arbiter is setting up. I think thats oke.

Delay can be small for example 1ms, its only to not drown out the CPU. At 25ms delay you get multiple frames of unfocused rimworld and visible arbiter.
You should do `if (Environment.OSVersion.Platform.Equals(PlatformID.Win32NT))` before starting the Task so it doesnt start an empty Task on Linux/mac.
You dont need `var arbiterHidden`, check for `CheckIfArbiterVisible()` in the while loop instead.

**Comment by Noires** [comment]
Quickly changed those things and removed `CheckIfArbiterVisible()` since it is not consistent.

**Comment by Zombiefied7** [comment]
Yep I like this now, looks beautiful!

Tho you can remove `var completed` and put `while(Multiplayer.session?.arbiter != null && !Multiplayer.session.ArbiterPlaying)` and it will be more beautiful.

We dont need `Multiplayer.session?.arbiter != null` because this is always true here. We might want to check `Multiplayer.session != null` before doing `Multiplayer.session.ArbiterPlaying` because it might crash but `Multiplayer.session != null` should always be true too so eh im not sure.

Task.Delay actually doesnt work like this. There is no delay and we need to find another solution or settle for a drowned CPU (doesnt seem to drown too much for me)

**Comment by Zombiefied7** [comment]
If we leave the savegame to menu while ArbiterHider is running, ArbiterHider never closes

**Comment by Zombiefied7** [comment]
`internal static void HideArbiterProcess()
        {
            if (Environment.OSVersion.Platform.Equals(PlatformID.Win32NT))
            {
                Task task = Task.Run(() =>
                {
                    while(Multiplayer.session != null && !Multiplayer.session.ArbiterPlaying)
                    {
                        FocusRimworld();
                        HideArbiter();
                        //Task.Delay(1); Does nothing needs a new solution
                    }
                });
            }
        }`

This fixes the main menu problem

**Comment by Zombiefied7** [comment]
You can make the task an async delegate like this `Task.Run(async delegate {` and then do `await Task.Delay(1);` and then it will work

**Comment by Noires** [comment]
Yeah just didn't think it would be necessary but here are the changes.

**Comment by Nebual** [comment]
I tested this out, and while it did work, alt-tab being entirely locked out while the Arbiter connects is a little off-putting.

I tried playing with alternatives like using https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.processstartinfo.createnowindow?view=netframework-4.8#System_Diagnostics_ProcessStartInfo_CreateNoWindow but it had no effect, possibly because the white window we're seeing is launched by some internal Unity command well after the initial rimworld.exe we're calling (which is probably the one being hidden by `-batchmode`).

Instead, I found this patch provided a smoother experience:
https://github.com/Nebual/Multiplayer/commit/1eb9c271992b545640c6f192c1285277a4de782c

There's a flash when the arbiter first boots, but we're returned to Rimworld's window fine. Another flash when the arbiter connects, and then its smooth.

You can accept my commit to your branch via
```
git remote add nebual https://github.com/Nebual/Multi
player.git
git fetch nebual
git cherry-pick nebual/arbiter-white-window-hider-neb
git push
```
(or just manually copy-paste the few lines)

**Comment by Noires** [comment]
@Zombiefied7 Can you confirm those changes?

**Comment by Deathlymad** [comment]
@Nebual we tried different approaches, noire referenced the original pull request where we logged it.

**Comment by Zombiefied7** [comment]
I like some of your ideas @Nebual for example using `SW_SHOWDEFAULT 10` instead of `SW_SHOWMAXIMIZED 3` as it uses the startup settings (previous resolution etc) but that setting sometimes pushes RimWorld on my second monitor. You did not suggest this actively but you did something to prevent using 10 which made me think that 10 might be better.

Then youre using the return value of ShowWindow() which is a good idea but for me it works inconsistently ie sometimes it doesnt refocus correctly.

So it comes down to a tradeoff on the one hand breaking alt+tab but very consistent on the other hand inconsistent but alt+tab is working.

**Comment by Noires** [comment]
Reverted latest changes. Ready for testing on other systems.

**Comment by notfood** [comment]
Squashing this one

**Pull request merged**
