### PR TITLE
Added lowest speed wins functionality

### PR DESCRIPTION
**Pull request by lukehedin**
**Details**

This change allows each player to select a preference for the game's speed. The lowest selected speed will always win. Preferences are sent from client to the server. The server checks the lowest speed any time a preference is updated.

In the upper right corner of the UI there is a second time display with numbers indicating how many players prefer each speed. Hovering over each speed will display the names of players with that preference.

**Concerns**

1. My main remaining concern is around how this will work in future with async map time, as seen by the two TODOs in "HandleTimeSpeedPref".
2. While joining the a multiplayer game, the speed preference display may not update until other players have CHANGED their preference. However, the server will still always sent the correct speed.

**If you'd like to try it out, a download of the current Multiplayer mod that includes this functionality and other minor bug fixes (including the recent dialog softlock fix) is available here:** https://mega.nz/#!Sz4FEagK!gNoHB0NEaP4r0-qPb4QzpvRMmz7iMt5ERyfXr7qr3DM

### CODE REVIEW

**Comment by notfood** [comment]
Please make it an option

**Comment by lukehedin** [comment]
> Please make it an option

Shall do!

**Comment by SweptWasTaken** [comment]
You ever gonna make this an option?

**Comment by lukehedin** [comment]
As mentioned, I'll have to butcher it and make another PR once 1.1 is safe.

**Comment by SweptWasTaken** [comment]
Closing this as 1.1 has there hasn't been any activity on it and it's probably outdated anyway...

**Pull request closed without merging**
