### PR TITLE
Added pre/post sync methods for SyncMethods

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
This works similar as pre/post invoke, except it's called before/after the data for method syncing is prepared and sent to the rest of the clients, but before actually syncing it.

Needs this PR for full functionality: https://github.com/rwmt/MultiplayerAPI/pull/2

### CODE REVIEW

**Review by notfood — CHANGES_REQUESTED** [review]
Is that `method.Invoke` correct?

DoSync isn't supposed to call `Invoke`, it's supposed to tell all clients there is a command to add to the execution queue for the next tick. The clients will execute the method on their own. Check what `Multiplayer.Client.SendCommand` does

**Comment by SokyranTheDragon** [comment]
Unless I'm misunderstanding something, I believe this should be correct. The point of this was to cancel syncing of the method and invoke the method for the client who called it without synchronizing it with the rest of the clients.

An example of a situation where it would be useful is when the method itself has a success state, that we want to sync, and a failure state, where it either does nothing or shows some message, dialog, or warning.

**Comment by notfood** [comment]
I see. I'm still hesitant about DoSync calling Invoke prematurely. When you call Sync you expect it to go to the queue. I'd rather add something along the lines of SyncMethod.CancelIfXXX and not invoke if it failed the test.

What do @Zetrith @Nebual think?

**Comment by SokyranTheDragon** [comment]
Closing as this is basically dead.

**Pull request closed without merging**
