### PR TITLE
Made it possible to select player colors

### PR DESCRIPTION
**Pull request by SokyranTheDragon**

### CODE REVIEW

**Review by notfood — COMMENTED** [review]
Do you know what happens when the user removes all colors and tries to host?

**Comment by SokyranTheDragon** [comment]
I made sure to leave at least a single color - I've added a check when removing them, and don't let the last one get removed. See here:
https://github.com/rwmt/Multiplayer/pull/286/files#diff-482a42081fed22af122e4b757da6fb395c3208058f6519fb6d9bf02fc6d3f0efR248

And if someone edited the settings to have no colors/leave a null list, it should restore default values:
https://github.com/rwmt/Multiplayer/pull/286/files#diff-482a42081fed22af122e4b757da6fb395c3208058f6519fb6d9bf02fc6d3f0efR79

**Review by notfood — APPROVED** [review]

**Comment by SokyranTheDragon** [comment]
Made a small change to use seeded random (if possible) for new colors. When adding a new color to the list, it'll randomly generate the color. With this change, it won't mess with RNG state if inside of an MP game.

As a side note: the colors are determined by the host. Should I add a label to the color selection screen about that?

**Comment by notfood** [comment]
I feel each player should present a color on connect, if it's duplicated, then the host gets to give it a random.

**Comment by SokyranTheDragon** [comment]
Just to clarify, do you mean something along the lines of:
Player connects -> sends their preferred color to the host -> if duplicate, host picks a random color (from their list?)?

So, basically treating the first color on the list as "player preferred color"? I'll be honest, not 100% sure at the moment how to implement something like this right now, would have to look deeper into how connecting works.

Also, a small issue with this approach would be similar colors (like one value being off by 1) - they'd still be allowed. But then being honest, would this be an issue? I'd assume it's something players could figure out between themselves.

**Comment by notfood** [comment]
You're right, players can figure that themselves. This would be nice to have in the future.
> Player connects -> sends their preferred color to the host

**Review by notfood — APPROVED** [review]

**Comment by SokyranTheDragon** [comment]
I've looked a bit into how the preferred color could be sent. One idea I have is to send it over with the `Client_JoinData` packet. We'd send the client join data before here:

https://github.com/rwmt/Multiplayer/blob/927c26f86b873fbfa1632bf64595d504a17b35c7/Source/Client/Networking/State/ClientJoiningState.cs#L57

And read it before here:

https://github.com/rwmt/Multiplayer/blob/e87aed579197bfa669aecb212aa8125ff1da39d0/Source/Common/Networking/State/ServerJoiningState.cs#L108

However, considering what it'd be modifying, I feel somewhat reluctant to change it. Any thoughts on this? Or better ideas on how to implement it?

**Comment by notfood** [comment]
We'd just need to bump the protocol, but then, it was never good to have different versions connect to each other even if protocol was unchanged.

From cursory look, it seems safe to do it on JoinData. Go for it.

**Pull request merged**
