### PR TITLE
Updates and additions to API

### PR DESCRIPTION
**Pull request by SokyranTheDragon**
It's going to require changes to MP API as well to work rwmt/MultiplayerAPI#9

Almost all of the changes done to match changes to API.

The only change besides that is adding support for `MethodType.Enumerator` in MpMethodUtil

### CODE REVIEW

**Comment by SokyranTheDragon** [comment]
Also, build is failing due to the MP API not having those changes included in yet

**Comment by SokyranTheDragon** [comment]
Merged in changes from #292

**Comment by Zetrith** [comment]
This is now addressed in part by #387

**Comment by SokyranTheDragon** [comment]
Matched changes with rwmt/MultiplayerAPI#9

**Comment by SokyranTheDragon** [comment]
Matched changes with rwmt/MultiplayerAPI#9 by adding `InInterface` to the API

**Pull request merged**
