### PR TITLE
Handle null hediffs in hediff sync worker

### PR DESCRIPTION
**Pull request by SokyranTheDragon**

### CODE REVIEW

**Comment by notfood** [comment]
Probably bad idea. What code requires it?

**Comment by SokyranTheDragon** [comment]
Trying to sync a method `void Close(Hediff hediff)`. It works fine, unless the provided hediff is null. It leaves me with the 2 following errors:

https://gist.github.com/SokyranTheDragon/0480320f4274645452c457225d8ae98f
https://gist.github.com/SokyranTheDragon/b6252333fa00bb9d94773ba39f13c0fb

**Comment by notfood** [comment]
Use `CancelIfValueNull`, don't pass the nulls to other clients. The syncworkers should assume the input object is not null.

**Comment by SokyranTheDragon** [comment]
I believe you meant `CancelIfAnyArgNull`, as the one you mentioned is for `ISyncField`.

However, the issue with that is:
1. Null is a valid value in that context - it's simply ignored in that context, while rest of the method is allowed to run
2. `CancelIfAnyArgNull` is only relevant after syncing - which means that SyncWorker is still trying to sync a null Hediff and causing the same 2 errors I posted earlier.

**Comment by notfood** [comment]
Very hesitant about this one but it doesn't hurt to have it.

**Pull request merged**
