### PR TITLE
MSBuild task to automatically publicise the rimworld dll.

### PR DESCRIPTION
**Pull request by Kuinox**
Hello there o/
Currently the publicised dll must be created with the publicise tool that you should download on another repository.
This PR allow to build the project without any manual extra step.

### CODE REVIEW

**Comment by notfood** [comment]
Does it need the spaces to tabs change?

**Comment by Kuinox** [comment]
Didn't paid attention to. Add an .editorconfig so VS/other editors will respect your conventions.

**Comment by lukaschristmann** [comment]
Can we pull this into wip-1.1? i've seen lots of confusion about the usage of publicice.exe in the development setup phase, i think this is nice to have...

**Comment by notfood** [comment]
Two things:
- Rebuilds it everytime you try to build the project.
- It fails on my setup.

**Comment by Kuinox** [comment]
Can i get any error/logs so i can guess/fix why it fails ?

**Comment by lukaschristmann** [comment]
> 
> 
> Two things:
> 
>     * Rebuilds it everytime you try to build the project.
> 
>     * It fails on my setup.

- From a fast test, it detects whether the public assembly is there or not costing almost no time on a build.
- Works for me (Windows+VS)

I gathered you're on Linux, what ide etc are you using? i'd like to make this work :-)

**Comment by Kuinox** [comment]
There is a condition on each build step that don't do the work is it was already done: 
If the Publicize zip is here, it don't download it.
If the zip is already unziped, it don't unzip again.
It run the Publicize step everytime, but the tool don't do anything if the rimworld dll have not changed.

**Comment by notfood** [comment]
I'll cherry pick it into wip

**Comment by Kuinox** [comment]
I changed the base branch, this is fine or i'll open a new PR ?

**Pull request merged**
